# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.Member'),
            preserve_default=False,
        ),
    ]
