# Generated by Django 2.1.3 on 2018-11-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_day_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='coment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
